const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (s) => ipcRenderer.invoke('save-settings', s),
  getVersions: () => ipcRenderer.invoke('get-versions'),
  login: () => ipcRenderer.invoke('ms-login'),
  offlineLogin: (u) => ipcRenderer.invoke('offline-login', u),
  getAccount: () => ipcRenderer.invoke('get-account'),
  logout: () => ipcRenderer.invoke('logout'),
  launch: (opts) => ipcRenderer.invoke('launch', opts),
  stopGame: () => ipcRenderer.invoke('stop-game'),
  onGameStarted: (cb) => ipcRenderer.on('game-started', () => cb()),
  onGameClosed: (cb) => ipcRenderer.on('game-closed', (_, v) => cb(v)),
  searchModrinth: (q, loader, mc, kind) => ipcRenderer.invoke('search-modrinth', q, loader, mc, kind),
  contentDownload: (kind, pid, loader, mc) => ipcRenderer.invoke('content-download', kind, pid, loader, mc),
  contentList: (kind) => ipcRenderer.invoke('content-list', kind),
  contentDelete: (kind, n) => ipcRenderer.invoke('content-delete', kind, n),
  openContentFolder: (kind) => ipcRenderer.invoke('open-content-folder', kind),
  friendSync: (d) => ipcRenderer.invoke('friend-sync', d),
  openGameDir: () => ipcRenderer.invoke('open-game-dir'),
  lastCrash: () => ipcRenderer.invoke('last-crash'),
  skinList: () => ipcRenderer.invoke('skin-list'),
  skinImport: () => ipcRenderer.invoke('skin-import'),
  skinDelete: (f) => ipcRenderer.invoke('skin-delete', f),
  skinApply: (f, v) => ipcRenderer.invoke('skin-apply', f, v),
  friendsList: () => ipcRenderer.invoke('friends-list'),
  friendAdd: (n, a) => ipcRenderer.invoke('friend-add', n, a),
  friendDelete: (n) => ipcRenderer.invoke('friend-delete', n),
  friendPing: (a) => ipcRenderer.invoke('friend-ping', a),
  inviteCreate: (a) => ipcRenderer.invoke('invite-create', a),
  inviteAccept: (c, n) => ipcRenderer.invoke('invite-accept', c, n),
  modsList: () => ipcRenderer.invoke('mods-list'),
  modDownload: (pid, loader, mc) => ipcRenderer.invoke('mod-download', pid, loader, mc),
  modDelete: (n) => ipcRenderer.invoke('mod-delete', n),
  openModsFolder: () => ipcRenderer.invoke('open-mods-folder'),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  installUpdate: () => ipcRenderer.invoke('quit-and-install'),
  repairVersion: () => ipcRenderer.invoke('repair-version'),
  serversList: () => ipcRenderer.invoke('servers-list'),
  serverAdd: (d) => ipcRenderer.invoke('server-add', d),
  serverDelete: (id) => ipcRenderer.invoke('server-delete', id),
  serverStart: (id) => ipcRenderer.invoke('server-start', id),
  serverStop: (id) => ipcRenderer.invoke('server-stop', id),
  serverCmd: (id, c) => ipcRenderer.invoke('server-cmd', id, c),
  serverSetAddress: (id, address) => ipcRenderer.invoke('server-set-address', id, address),
  playitStatus: () => ipcRenderer.invoke('playit-status'),
  playitStart: () => ipcRenderer.invoke('playit-start'),
  playitStop: () => ipcRenderer.invoke('playit-stop'),
  serverModpackGet: (id) => ipcRenderer.invoke('server-modpack-get', id),
  serverModpackMeta: (id, loader, mc) => ipcRenderer.invoke('server-modpack-meta', id, loader, mc),
  serverModpackAdd: (id, pid, loader, mc) => ipcRenderer.invoke('server-modpack-add', id, pid, loader, mc),
  serverModpackRemove: (id, pid) => ipcRenderer.invoke('server-modpack-remove', id, pid),
  serverModpackCode: (id) => ipcRenderer.invoke('server-modpack-code', id),
  modpackInstallCode: (code) => ipcRenderer.invoke('modpack-install-code', code),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  onPlayitState: (cb) => ipcRenderer.on('playit-state', (_, v) => cb(v)),
  serverLogGet: (id) => ipcRenderer.invoke('server-log-get', id),
  onServerLog: (cb) => ipcRenderer.on('server-log', (_, v) => cb(v)),
  onServerState: (cb) => ipcRenderer.on('server-state', (_, v) => cb(v)),
  bedrockStatus: () => ipcRenderer.invoke('bedrock-status'),
  bedrockLaunch: () => ipcRenderer.invoke('bedrock-launch'),
  skinsLibrary: () => ipcRenderer.invoke('skins-library'),
  skinImport: () => ipcRenderer.invoke('skin-import'),
  skinApply: (n, m, x) => ipcRenderer.invoke('skin-apply', n, m, x),
  onLog: (cb) => ipcRenderer.on('launch-log', (_, v) => cb(v)),
  onProgress: (cb) => ipcRenderer.on('launch-progress', (_, v) => cb(v)),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_, v) => cb(v)),
  onUpdateReady: (cb) => ipcRenderer.on('update-ready', () => cb())
});
