window.api = {
  getSettings: async () => ({ ramMin: '2G', ramMax: '4G', javaPath: '', gameDir: 'C:\\jogo', resolution: { width: 854, height: 480 }, version: '1.21.1', loader: 'fabric', overlay: true, displayMode: 'borderless', autoUpdate: true }),
  saveSettings: async () => true,
  getVersions: async () => ['1.21.1', '1.21', '1.20.4'],
  login: async () => ({ name: 'Steve', type: 'microsoft' }),
  offlineLogin: async (u) => ({ name: u, type: 'offline' }),
  getAccount: async () => ({ name: 'Steve', type: 'offline' }),
  logout: async () => true,
  launch: async () => true,
  searchModrinth: async () => ({ hits: [{ title: 'Sodium', project_id: 'abc', downloads: 123456, description: 'Motor gráfico moderno para Fabric.', categories: ['fabric'], versions: ['1.21', '1.21.1'] }] }),
  modDownload: async () => ({ file: 'sodium-1.21.1.jar', version: '0.6', skipped: false }),
  contentDownload: async () => ({ file: 'x.zip', version: '1.0', skipped: false }),
  modsList: async () => [{ name: 'sodium-1.21.1.jar', size: 2048000 }],
  contentList: async () => [],
  modDelete: async () => true,
  contentDelete: async () => true,
  openModsFolder: async () => true,
  openContentFolder: async () => true,
  openGameDir: async () => true,
  lastCrash: async () => ({ file: null, head: '' }),
  checkUpdate: async () => true,
  installUpdate: async () => true,
  onLog: () => {}, onProgress: () => {}, onUpdateStatus: () => {}, onUpdateReady: () => {}
};
