name: Release
# Publica o setup no GitHub Releases sempre que você criar uma tag v*
# Ex: npm version patch && git push && git push --tags
on:
  push:
    tags: ['v*']
jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --no-audit --no-fund
      - run: npx electron-builder --win nsis portable --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
